# Generated by Django 3.2.3 on 2021-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210623_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='age',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='gender',
            field=models.CharField(default='Male', max_length=250),
        ),
        migrations.AddField(
            model_name='register_table',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='register_table',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
